package pluginapi

import "time"

const (
	// Version is the plugin API compatibility marker.
	Version = "chainops.pluginapi/v1alpha1"
)

// DiagnosticSeverity classifies plugin validation results.
type DiagnosticSeverity string

const (
	SeverityError   DiagnosticSeverity = "error"
	SeverityWarning DiagnosticSeverity = "warning"
)

// Diagnostic is a plugin-facing validation/error payload.
type Diagnostic struct {
	Severity DiagnosticSeverity `json:"severity" yaml:"severity"`
	Path     string             `json:"path,omitempty" yaml:"path,omitempty"`
	Message  string             `json:"message" yaml:"message"`
	Hint     string             `json:"hint,omitempty" yaml:"hint,omitempty"`
}

// Artifact is a deterministic file contribution generated by a plugin.
type Artifact struct {
	Path    string `json:"path" yaml:"path"`
	Content string `json:"content" yaml:"content"`
}

// Capabilities advertises supported lifecycle operations.
type Capabilities struct {
	SupportsMultiProcess bool `json:"supportsMultiProcess" yaml:"supportsMultiProcess"`
	SupportsBootstrap    bool `json:"supportsBootstrap" yaml:"supportsBootstrap"`
	SupportsBackup       bool `json:"supportsBackup" yaml:"supportsBackup"`
	SupportsRestore      bool `json:"supportsRestore" yaml:"supportsRestore"`
	SupportsUpgrade      bool `json:"supportsUpgrade" yaml:"supportsUpgrade"`
}

// Metadata documents plugin build metadata.
type Metadata struct {
	Name        string    `json:"name" yaml:"name"`
	Version     string    `json:"version" yaml:"version"`
	BuiltAt     time.Time `json:"builtAt" yaml:"builtAt"`
	APIVersion  string    `json:"apiVersion" yaml:"apiVersion"`
	Description string    `json:"description,omitempty" yaml:"description,omitempty"`
}

// Output is the plugin payload consumed by execution backends.
type Output struct {
	Artifacts []Artifact        `json:"artifacts,omitempty" yaml:"artifacts,omitempty"`
	Metadata  map[string]string `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Warnings  []Diagnostic      `json:"warnings,omitempty" yaml:"warnings,omitempty"`
	Info      map[string]any    `json:"info,omitempty" yaml:"info,omitempty"`
}
